version: '3'

services:
  laratrack_nginx:
    build: ./nginx
    links:
      - laratrack_web
      - laratrack_socket
    ports:
     - "8081:80"
  laratrack_web:
    build: ./
    volumes:
      - ./:/var/www/html
    expose:
      - '80'
  laratrack_socket:
    build: ./websocket
    volumes:
      - ./websocket/:/usr/src/app
    restart: always
    expose:
      - '3000'
    links:
      - laratrack_redis
  laratrack_redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
